### ISSUE TITLE
I think you may have leaked a private key

### ISSUE THREAD

**Issue by Khaoz-Topsy** [BrockBeldham/nms-wiki-boilerplate#1]
[https://github.com/BrockBeldham/nms-wiki-boilerplate/blob/main/gh-pages](https://github.com/BrockBeldham/nms-wiki-boilerplate/blob/main/gh-pages)

Not sure if this is of an old account, but best to remove it and then revoke it i.m.o. If you just delete it in the repo then it will still be in the history of the repo.

**Comment by BrockBeldham** [comment]
Thanks, good catch. It's actually a placeholder key from a previous deploy strategy and I just forgot to remove the files. The keys were never created in the first place. I've removed the package in question along with the key files it created.
